### ISSUE TITLE
Add fa-snapchat-o

### ISSUE THREAD

**Issue by jackvial** [jackvial/fa-snapchat#5]
Add alternate version of the icon

**Comment by ShaunR** [comment]
Yes, when would you be able to do this!?

The current icon is solid, so i'm assuming this one would be the ghost being transparent but with a stroke/outline around it?

**Comment by jackvial** [comment]
Hi Shaun, I'm not sure when I will have the time but you're welcome to have a go at it and create a PR to this repo. I used this https://icomoon.io/app/#/select to generate the font files for the icon.

**Comment by ShaunR** [comment]
You can close out this issue, font awesome added snapchat.  This repo is no longer needed.

**Comment by jackvial** [comment]
@ShaunR It still serves as a useful starting point for adding new icons that are not yet support by fontawesome.
